### ISSUE TITLE
Pass options to docker-compose

### ISSUE THREAD

**Issue by leighmcculloch** [leighmcculloch/vagrant-docker-compose#10]
It could be useful to be able to configure additional options that get passed to the docker-compose commands that run, or to be able to explicitly define the docker-compose commands that run on `up`.

Idea came from [this StackOverflow comment](http://stackoverflow.com/questions/30665816/docker-compose-vagrant-and-insecure-repository?rq=1#comment49395344_30665816).

**Comment by petarmaric** [comment]
This would be a great option, as I would like to set a custom `timeout` for `docker-compose up`.

**Comment by annymsMthd** [comment]
+1 would also be useful for passing the --x-networking flag

**Comment by leighmcculloch** [comment]
@petarmaric @annymsMthd To give full flexibility, I'm considering not adding any options for this, and instead writing a short piece for the README Usage section on how to fully customize the commands run on start using a `shell` provisioner. What do you think?

**Comment by teohhanhui** [comment]
I think that defeats the purpose of having this plugin. As we know, `docker-compose` is only a single binary, so what does this plugin bring to the table?

**Comment by leighmcculloch** [comment]
@petarmaric @annymsMthd @teohhanhui What do you think of #19?

**Comment by petarmaric** [comment]
@leighmcculloch I think that's a great idea. Simple use cases are still simple, and complex ones are possible. Good job man :)

**Comment by leighmcculloch** [comment]
This is in version `0.0.8`.

Options can be passed to the executable.

```ruby
config.vm.provision :docker_compose,
  options: "--x-networking",
  yml: "/vagrant/docker-compose.yml",
  run: "always"
```

Results in:
```
docker-compose --x-networking -f [yml] up -d
```

And options can be passed to the `build`, `rm`, and `up` commands.

```ruby
config.vm.provision :docker_compose,
  yml: "/vagrant/docker-compose.yml",
  command_options: { up: "-d --timeout 20" },
  run: "always"
```

Results in:
```
docker-compose -f [yml] up -d --timeout 20
```

**Comment by annymsMthd** [comment]
+1 simple and it will keep up with new commands. You can always go back and
strongly type the major ones

**Comment by teohhanhui** [comment]
:+1:
