### ISSUE TITLE
Re-download docker-compose binary when compose_version is changed

### ISSUE THREAD

**Issue by teohhanhui** [leighmcculloch/vagrant-docker-compose#12]

**Comment by leighmcculloch** [comment]
To support this I think it will make sense to download `docker-compose` to a file that has the version number in it and symlink the current version. Then on run it can check for the presence of the specific version and download it if necessary, and then change the symlink as well.

**Comment by leighmcculloch** [comment]
@teohhanhui This was added in #24 and is now released in version `1.0.0`. Hope it's helpful!
