### ISSUE TITLE
docker-compose default version change to 1.5.0

### ISSUE THREAD

**Issue by jgrecoarroyo** [leighmcculloch/vagrant-docker-compose#15]
Hi,

I like this plugin very much, and have been using it successfully; thanks for that. I will like to use some of the new features that docker-compose version 1.5.0 offers. The default version this plugin installs is 1.4.0.

I understand the latest version of this plugin (0.0.5) was released on Aug, and the new docker-compose release (1.5.0) was released barely one week ago.

Please I need help to understant:
 a) how to change the default release of docker-compose to 1.5.0 instead of 1.4.0, or
 b) how to use the "compose_version" config (as specified at the end of the README.md)?

Thanks,
Juan

**Comment by leighmcculloch** [comment]
You can specify the `compose_version` manually, by adding the argument to your `Vagrantfile` like so:

```ruby
config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: true, run: "always", compose_version: "1.5.0"
```

In any case, version `0.0.6` of `vagrant-docker-compose` defaults to version `1.5.0` of `docker-compose` now. :smile:
