### ISSUE TITLE
Define project name in Vagranfile vagrant-docker-compose configuration.

### ISSUE THREAD

**Issue by chrisbrantley** [leighmcculloch/vagrant-docker-compose#2]
I'm not crazy about the "vagrant_" prefix for every container. Is it possible to override that in the vagrantfile?

**Comment by leighmcculloch** [comment]
@chrisbrantley This isn't something provided by vagrant-docker-compose, but it is possible.

The prefix on the container is based off the directory your Vagrantfile lives in. e.g. if my project is in a folder called `example`, it's going to look like this in VirtualBox.
![screen shot 2015-06-03 at 8 05 55 am](https://cloud.githubusercontent.com/assets/351529/7963420/7dcb7ae8-09c7-11e5-9aa8-fea4d2359407.png)

The second part of the name `web` comes from a `config.vm.define "web"` line in my Vagrantfile.

If you want to customize the exact name and you're using VirtualBox as the provider, you can follow the instructions [here](http://docs.vagrantup.com/v2/virtualbox/configuration.html) to change the name of the virtual machine.

**Comment by chrisbrantley** [comment]
@leighmcculloch Thanks for the reply.

I also found that docker-compose will use an environment variable (COMPOSE_PROJECT_NAME) so I added the following to my Vagrantfile

```
config.vm.provision "shell" do |s|
    s.inline = 'echo "export COMPOSE_PROJECT_NAME=<my_project_name>" >> ~/.profile'
end
```

This works, albeit a little clunky.

**Comment by leighmcculloch** [comment]
Ahh, I misunderstood your question. You're wanting to rename the prefix of the docker images that are inside the vagrant instance. I think I can add setting the docker-compose project name as a configuration value of `vagrant-docker-compose` so that you don't need to have the repetitive shell inline in each of your projects. I'll get back to you when it's in the next version of this.

**Comment by chrisbrantley** [comment]
Thank you. I'm sorry if my question wasn't clear.  Having a setting on the vagrant-docker-compose configuration would be very handy and much cleaner.

**Comment by leighmcculloch** [comment]
This is in version `0.0.3` now, just add a `project_name` parameter to the docker_compose provision statement. See `example/Vagrantfile`.
