### ISSUE TITLE
Support for docker-compose run

### ISSUE THREAD

**Issue by sandrokeil** [leighmcculloch/vagrant-docker-compose#20]
Is it possible to add support for the run command of docker-compose? So i can do the following in the Vagrantfile:

```
config.vm.provision :docker

config.vm.provision :docker_compose, compose_version: "1.5.1", yml: "/vagrant/docker-compose.yml", rebuild: false, run: "always"

config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: false,
            command_options: { run: "--rm php sh bin/setup_mysql.sh"}, run: "always"
```

With this i can run an install script.

**Comment by leighmcculloch** [comment]
I could make it call the run command after `up` if run options are defined. But that would only allow for a single `run` command.

Questions: 

1. Would it be useful to be able to call run multiple times? 
2. Is there a way to trigger the `run` with your parameters from within the `yml` file?

**Comment by sandrokeil** [comment]
> 1. Would it be useful to be able to call run multiple times?

Yes, it depends on what to setup. Maybe you want to configure different containers. For clarification, here are the native Docker commands (pseudo):

```cli
$ docker run mysql ...
$ docker run php ...
$ docker run nginx ...
$ docker run --rm -it php bash ./setup.sh (call a PHP script which needs the MySQL container)
```
The first three commands are handled by Docker Compose and the fourth command is for convenience for the user to try out the demo.

> 2. Is there a way to trigger the run with your parameters from within the yml file?

No, because this is only for convenience for the user to try out the demo. It's out of scope of the docker-compose.yml file.

In my case, I need the PHP container with the link to the MySQL container to run a PHP script which setups the database (Doctrine Migrations).

**Comment by leighmcculloch** [comment]
So you can get going with this now, you should be able to do this with:

```
config.vm.provision :shell, inline: "docker-compose run --rm --it php bash ./setup.sh"
```

**Comment by sandrokeil** [comment]
@leighmcculloch Of cource, that works. So there is nothing to change. Thanks.
