### ISSUE TITLE
Multiple docker-compose files

### ISSUE THREAD

**Issue by SEAnderson07** [leighmcculloch/vagrant-docker-compose#21]
Is it possible to use multiple docker-compose files in the Vagrantfile with this provisioner? I am looking to be able to mimic running `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up` on vagrant up. Thanks!

**Comment by leighmcculloch** [comment]
Yup we can do this. I think what we'll do is we'll make the file parameter optionally be an array. So it can be a string or an array, and if it's an array, they'll be used with multiple `-f`s.

**Comment by leighmcculloch** [comment]
@SEAnderson07 this is in version 0.0.9 now! :smile:
