### ISSUE TITLE
Support for v2 compose files

### ISSUE THREAD

**Issue by cternes** [leighmcculloch/vagrant-docker-compose#26]
I've noticed that there is no support for v2 compose files. Have you considered implementing support for v2 files?

**Comment by leighmcculloch** [comment]
Version 2 docker-compose files work out of the box if you change the `compose_version` value to `1.6.2`, then you can use either version 1 or 2 in the YAML. I'll make 1.6.2 the default version soon too that gets installed.

**Comment by leighmcculloch** [comment]
I've just shifted the default `compose_version` to `1.6.2`, so you should be able to use version `2` compose files now. You'll need to run `vagrant plugin install vagrant-docker-compose` to get the latest version, `0.0.10`.

**Comment by cternes** [comment]
Works like a charm, thanks!

**Comment by leighmcculloch** [comment]
![](http://jif.wtf/00.opmIBtljGbwZi.gif)
