### ISSUE TITLE
compose_version check, and auto-update

### ISSUE THREAD

**Issue by desm** [leighmcculloch/vagrant-docker-compose#28]
Hi. I have been using the following line in my Vagrantfile for the past little while:

`pocket.vm.provision :docker_compose, compose_version: "1.6.0"`

I was hoping that setting the version to 1.7.0 (released 8 days ago) would auto-magically upgrade docker-compose, but it does not. One thing that did work however was to delete /usr/local/bin/docker-compose and do a 'vagrant reload'. Maybe the plugin could check to see if the version installed matches the compose_version option? Just an idea, thanks!

**Comment by leighmcculloch** [comment]
Version `1.0.0` was released 15 days ago and has the exact feature you're asking for 😄 . Ref: #24.

What version of `vagrant-docker-compose` do you have installed? You can check by running:

```shell
$ vagrant plugin list
```

If it's below `1.0.0` you can update by doing the following:

```shell
$ vagrant plugin update vagrant-docker-compose
```

If you already have `1.0.0`, there might be a bug and we can investigate.

**Comment by desm** [comment]
Thanks Leigh, much appreciated. I did not think of upgrading the plugin! I will try again and let you know if the newer version of the plugin upgrades docker-compose from 1.6.0 to 1.7.0 smoothly or not. Cheers.

**Comment by desm** [comment]
It worked. I reverted to version 1.6.0 in the linux vm by removing docker-compose from /usr/local/bin, then setting the version back to 1.6.0 in the Vagrantfile and doing a `vagrant reload --provision`.

Then I upgraded your plugin, set compose_version to 1.7.0 in the Vagrantfile, then ran `vagrant reload --provision` and it upgraded docker-compose to 1.7.0. Thanks again.

**Comment by leighmcculloch** [comment]
Excellent! 👍
