### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by ISkomorokh** [leighmcculloch/vagrant-docker-compose#29]
Hi! Could you please help me. When trying to install this plugin I'm receiving the following error:

Vagrant version `1.8.3`. On another machine with Vagrant `1.8.1` it is working fine.

$ `vagrant plugin install vagrant-docker-compose`
Installing the 'vagrant-docker-compose' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.

What could be done to resolve that?

Thanks

**Comment by ISkomorokh** [comment]
Ok, I'm closing this issue. To resolve it I had to install Vagrant `1.8.4`. The problem was - there were no such an installer on an official site. I used cocolatey to install it [vagrant latest](https://chocolatey.org/packages/vagrant)

**Comment by leighmcculloch** [comment]
@ISkomorokh What platform/OS was this happening on? Were you using the ruby gem version of vagrant or the official installer from https://www.vagrantup.com/downloads.html?

**Comment by ISkomorokh** [comment]
@leighmcculloch Windows 8.1 x64

> Were you using the ruby gem version of vagrant or the official installer from https://www.vagrantup.com/downloads.html?

The official installer
