### ISSUE TITLE
example doesn't work out of the box

### ISSUE THREAD

**Issue by cappetta** [leighmcculloch/vagrant-docker-compose#31]
I'm trying to get this plugin working and currently debugging the issue.  I tested the example as it does not work out of the box as expected.  I'll post a message if I figure out how to solve this problem...

> root@UbuntuServe-0:~/vagrant-docker-compose/example#

>  vagrant status
> No usable default provider could be found for your system.
> 
> Vagrant relies on interactions with 3rd party systems, known as
> "providers", to provide Vagrant with resources to run development
> environments. Examples are VirtualBox, VMware, Hyper-V.
> 
> The easiest solution to this message is to install VirtualBox, which
> is available for free on all major platforms.
> 
> If you believe you already have a provider available, make sure it
> is properly installed and configured. You can see more details about
> why a particular provider isn't working by forcing usage with
> \`vagrant up --provider=PROVIDER\`, which should give you a more specific
> error message for that particular provider.
> root@UbuntuServe-0:~/vagrant-docker-compose/example# vagrant status --provider=docker
> An invalid option was specified. The help for this command
> is available below.
> 
> Usage: vagrant status [name]
>     -h, --help                       Print this help

`

**Comment by leighmcculloch** [comment]
@cappetta The error you're seeing is not an error relating to this plugin, it's an error relating to the setup of Vagrant on your machine. Vagrant, independently of this plugin, needs a provider to host VMs in. The simplest one to use is [VirtualBox](https://www.virtualbox.org/wiki/Downloads). Once you install VirtualBox `vagrant up` should work as expected in that directory.
