### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by Industrial** [leighmcculloch/vagrant-docker-compose#37]
Hi!

This seems to be installing Docker Compose v1.6.x, while the latest is 1.8.x.

I'm used to using docker compose with the --build flag, but that's not available in 1.6 but later.

gr,

Tom

**Comment by leighmcculloch** [comment]
Thanks @Industrial. I've updated the default version installed to 1.8.0. If you ever want to use a different version than the default you can [config the version manually](https://github.com/leighmcculloch/vagrant-docker-compose#other-configs), but either way the latest version (v1.2.0) has Docker Compose 1.8.0 now. 😄
