### ISSUE TITLE
Docker provisioner not running before docker-compose provisioner

### ISSUE THREAD

**Issue by syntacticvexation** [leighmcculloch/vagrant-docker-compose#38]
Hi,

When attempt to build my docker-compose boxes I get this error:

```
==> default: Running provisioner: docker_compose...
    default: Checking for Docker Compose installation...
    default: Symlinking Docker Compose 1.8.0
    default: Running docker-compose up...
==> default: mesg:
==> default: ttyname failed
==> default: :
==> default: Inappropriate ioctl for device
==> default: Couldn't connect to Docker daemon. You might need to install Docker:
==> default:
==> default: https://docs.docker.com/engine/installation/
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 /usr/local/bin/docker-compose-1.8.0  -f "/srv/docker/docker-compose.yml" up -d

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
```

Here is my Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "test.devel"

  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/srv/docker/docker-compose.yml", run: "always"
end
```

If I comment out the docker_composes provisioner line and allow docker to install then uncomment it and reprovision it works fine.

My understanding from the doco is that these should run sequentially:
https://www.vagrantup.com/docs/provisioning/basic_usage.html

Is there anything you can think of as to why this might be taking place?

Thanks.

**Comment by pacharanero** [comment]
I also encountered this error, and I couldn't find any documentation to explain why Docker wasn't being installed. 

After some experimentation, I was able to fix this by appending `, run: "always"` to the `config.vm.provision :docker` command thus:

`config.vm.provision :docker, run: "always"` as you have done with the docker-compose command. I can't work out why this would have the required effect, but it seems to work.

Marcus

**Comment by leighmcculloch** [comment]
Thanks @pacharanero. That's real odd, the `:docker` provisioner shouldn't require run always unless you uninstalled docker after the initial provision. Maybe something else in your instance is causing the instance to lose docker or maybe docker failed to install during the initial provision?

**Comment by h3christophe** [comment]
I had the same error and it was because on how my Vagrant file was written  

```
 config.vm.define boxName do |node|
 
       # Docker
        node.vm.provision :docker do |d|
              .....
        end

        # Docker Compose.
        config.vm.provision :docker_compose do |compose|
           ..........
        end

end
```

i used config.XXX for the docker_compose and node.XXX for the docker provisioner 
And because of that "docker_compose" was executed before "docker" and thus could not find docker 

Silly mistakes :)

**Comment by leighmcculloch** [comment]
Ah, thanks for explaining @h3christophe.
