### ISSUE TITLE
Installs docker-compose even if docker-compose is already installed

### ISSUE THREAD

**Issue by LukasVice** [leighmcculloch/vagrant-docker-compose#41]
In my vagrant box, docker-compose version 1.9.0 is installed in the /usr/local/bin directory.
When starting with vagrant up, the plugin checks for docker-compose but does not find it and installs docker-compose 1.8.0.
How does the plugin check if docker-compose is installed?
Thanks.

**Comment by leighmcculloch** [comment]
It checks if it is installed by [checking](https://github.com/leighmcculloch/vagrant-docker-compose/blob/master/lib/vagrant-docker-compose/cap/linux/docker_compose_installed.rb#L7-L13) if there is a file at the `executable_install_path`.

You can change the install path by overriding the [executable_install_path](https://github.com/leighmcculloch/vagrant-docker-compose#other-configs) param.

**Comment by LukasVice** [comment]
Ok, thanks.

I think it would be great if it would check the symlink path too, so you don't have to set the executable_install_path in each Vagrantfile (since the executable_install_path is per default with version number). Or maybe just check if it is in the PATH (if possible...)?

**Comment by leighmcculloch** [comment]
It checks if the specific version is installed so that if someone has vagrant installed and then they set the version to be a different version, it will download it and setup the symlink for it.

**Comment by leighmcculloch** [comment]
@LukasVice: Does your box already have docker-compose installed?

**Comment by jamiejackson** [comment]
Mine did. I removed the installation and let the plugin take over. Now it doesn't keep reinstalling.
