### ISSUE TITLE
Issue with example provided

### ISSUE THREAD

**Issue by Ilhicas** [leighmcculloch/vagrant-docker-compose#42]
Hello, so I've been trying to use the example. 
I'm still a new user to Vagrant, and Docker itself, but the problem was that whenever I did Vagrant Up 
I would get

Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

By ssh into VM problem would persist by doing docker version.

Solution was to change box used to Trusty64 in the Vagrantfile of example, and all is working.
Don't know if anyone else had the same issue, but this worked out for me.

**Comment by ed-alertedh** [comment]
I had the same issue. Specifically, I changed it to:
config.vm.box = "ubuntu/trusty64"

Possibly caused an incompatibility with the precise64 base image after a version bump for docker/docker-compose?

**Comment by carlosperate** [comment]
I can confirm that I had the same issue and upgrading to `config.vm.box = "ubuntu/trusty64"` solved it.

**Comment by leighmcculloch** [comment]
I've just bumped the example to use that image in 17a5c9f. Thanks!
