### ISSUE TITLE
Update to latest Docker Compose

### ISSUE THREAD

**Issue by lephleg** [leighmcculloch/vagrant-docker-compose#45]
Hello, 

First of all, great work! Please keep it up.

I'd like to ask if there are any known incompatibilities regarding the latest Docker Compose version (currently 1.11.2). I know that compose format has reached v3 with some options removed. 

Could these cause us a problem with Vagrant?

**Comment by leighmcculloch** [comment]
@lephleg: Would you like to try it with compose version 1.11.2 by [using](https://github.com/leighmcculloch/vagrant-docker-compose#other-configs) the `compose_version` parameter? If it works we can bump that up to the latest version, otherwise we can look at updating to the new compose version.

**Comment by das-peter** [comment]
@leighmcculloch / @lephleg For us 1.11.2 seems to work. All containers up and running.

**Comment by lephleg** [comment]
@das-peter Great news! @leighmcculloch I didnt have any issues either, so I think we could set 1.11.2 as the default version.

**Comment by leighmcculloch** [comment]
@das-peter: Thanks for confirming!

The latest version of the plugin (1.3.0) defaults to docker-compose 1.11.2.
