### ISSUE TITLE
Error while building a project

### ISSUE THREAD

**Issue by tux240** [leighmcculloch/vagrant-docker-compose#48]
Hello,

I started my vagrant up with this file:
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

        config.vm.provision :docker
        config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml",  run: "always", compose_version: "1.14.0"
end
```

It works well but there is a crash that return this error:
Service 'web' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 137

I don't know what append

Thanks

**Comment by leighmcculloch** [comment]
It sounds like one of your services in your docker compose is attempting to run `npm install` and is failing. Can you share your `docker-compose.yml` file?

**Comment by tux240** [comment]
I found the problem.
It was the memory that wasn't too hight. So I added:
`config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end`

But I found that, once my containers are launched, they are very slow...

**Comment by leighmcculloch** [comment]
Ah, yes you may need to alter the memory that vagrant assigns your instance.
