### ISSUE TITLE
Named Provisioner

### ISSUE THREAD

**Issue by jamiejackson** [leighmcculloch/vagrant-docker-compose#49]
I use named provisioners so I can rerun a specific one when I want to, e.g.:

```ruby
    config.vm.provision "install_less", type: "shell", path: "#{host_script_dir}/misc/install_less.sh",
      args: [
        "--provisioned-dir=#{vm_provisioned_dir}",
        "--runfile-name=install_less",
        "--script-dir=#{vm_script_dir}"
      ]
```
I can rerun that with `vagrant provision --provision-with=install_less`. How do I name a docker-compose provisioner?

**Comment by leighmcculloch** [comment]
You should be able to use named provisioners with this plugin also, by setting the type to `docker_compose` and setting a name prior to that. All the other options should work as normal.

**Comment by mbrodala** [comment]
I can confirm that this works as expected, here a working example:

```rb
config.vm.provision "proxy",
  type: "docker_compose",
  ...

config.vm.provision "app",
  type: "docker_compose",
  ...
```

**Comment by leighmcculloch** [comment]
Thanks for confirming @mbrodala !
