### ISSUE TITLE
'docker_compose' provisioner not found on Windows 10

### ISSUE THREAD

**Issue by maszaa** [leighmcculloch/vagrant-docker-compose#50]
I have VirtualBox, Vagrant and vagrant-docker-compose plugin installed. Running `vagrant up` causes the following error:
```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'docker_compose' provisioner could not be found.`
```

I've created the `Vagrantfile` based on the examples on the README. I've also tried to reinstall the `vagrant-docker-compose` and reboot the system.

I'm using Windows 10 64 bit, latest VirtualBox, Vagrant and vagrant-docker-compose. As VM box I'm using `ubuntu/trusty32` as I have Hyper-V enabled (VirtualBox can't use 64 bit images in that case).

The configuration worked with Windows 7 64 bit and with Vagrant 1.9.6.

**Comment by maszaa** [comment]
The issue was related to Hyper-V being enabled. Seems that VirtualBox can't be used with 64 bit images in that case.

**Comment by leighmcculloch** [comment]
Could you share what the contents of these locations are on disk?

```
%USERPROFILE%.vagrant.d\plugins.json
%USERPROFILE%.vagrant.d\gems\gems\vagrant-docker-compose
%USERPROFILE%.vagrant.d\gems\specifications\vagrant-docker-compose.gemspec
```

Ref: https://stackoverflow.com/a/36944454/159762

**Comment by neverwet** [comment]
@maszaa 

I had same problem on Windows 8 Professional. This error can causes because of non-latin characters in path to .vagrant.d folder.

I resolved it via moving .vagrand.d to another directory and changing this path in environment variable VAGRANT_HOME.

**Comment by leighmcculloch** [comment]
Closing as the information shared by @neverwet suggests this is an issue with vagrant on Windows. It might be worth opening an issue on the vagrant project itself if you folks haven't already: https://github.com/hashicorp/vagrant.
