### ISSUE TITLE
Don't rely on curl only

### ISSUE THREAD

**Issue by prilka** [leighmcculloch/vagrant-docker-compose#54]
For the download/installation of docker-compose curl is used inside of the vm. But not all images have curl preinstalled (e.g. `debian/stretch64`), which leads to the following error:

```
==> default: Running provisioner: docker_compose...
    default: Checking for Docker Compose installation...
    default: Installing Docker Compose 1.11.2
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose-1.11.2

Stdout from the command:



Stderr from the command:

bash: line 4: curl: command not found
```

The installation would be more robust if additional `wget` would be used. 
Something like:
```bash
URL=https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` ; (curl -L $URL || wget -O- $URL) > ...
```

**Comment by leighmcculloch** [comment]
Instead of `curl` the plugin should use the Ruby `Net::HTTP` class, then neither need be installed.

**Comment by prilka** [comment]
That's true, but then the download ist done on the host, not inside of the vm. If it's easy to transfer files to the vm, that would be the most elegant way.

**Comment by leighmcculloch** [comment]
@prilka This is in v1.5.0. Give it a go and let me know if it is 👍.

**Comment by prilka** [comment]
Good work. Works now without problems.
