### ISSUE TITLE
Copy files from a mounted directory to a Docker image

### ISSUE THREAD

**Issue by toedter** [leighmcculloch/vagrant-docker-compose#6]
My use case is:
I would like to copy files from a mounted directory (in Vagrantfile) to a Docker image.

Vagrantfile:
config.vm.synced_folder "./services", "/services", create: true

Dockefile:
COPY services/myapp.jar /app.jar

Since services has to be in the Docker build context, I cannot say
COPY /services/myapp.jar /app.jar

So it would help, if I could configure the Vagrant docker-compose provider to be run in a specific directory, e.g. "/"

An alternative would be to specify in the Vagrantfile:
config.vm.synced_folder "./services", "/directory-where-docker-compose-is-run/services", create: true

What is the default directory where docker-compose is run?

**Comment by toedter** [comment]
Hmm, could not get it working even when ssh in the vm and then manually invoke docker-compose from "/". Will investigate...

**Comment by leighmcculloch** [comment]
By default docker compose runs in the default directory of the instance that Vagrant uses as the default. This is usually `/vagrant`.

**Comment by toedter** [comment]
Thx for the reply.

Then I am wondering why "COPY services/myapp.jar /app.jar" in the Dockerfile is not working out of the box, since in the /vagrant directory there is the service directory....

**Comment by leighmcculloch** [comment]
Could you try using an absolute location in the COPY to see if that makes a difference. That's not an ideal situation but it might help us work out if maybe the working directory is a strange directory, and if so we can try fixing that.

**Comment by leighmcculloch** [comment]
@toedter did the absolute directory work?

**Comment by leighmcculloch** [comment]
Closing as this has become a stale issue.
