### ISSUE TITLE
[Feature] Add start support

### ISSUE THREAD

**Issue by sandrokeil** [leighmcculloch/vagrant-docker-compose#8]
It is possible to use the Docker Compose *start* option if the container exists and only use *up -d* at the first time (provision)? So *always* means:

```
docker-compose -f [yml] start
```

This would be great.

**Comment by leighmcculloch** [comment]
@sandrokeil Indeed I can add an option to control whether docker-compose is run as a daemon or not. If it's not run as a daemon though docker is likely to be killed when the provisioning script finishes or the provision script will run forever. Is that what you're wanting to happen?

**Comment by sandrokeil** [comment]
@leighmcculloch I want an option which does the following ;-)

* `vagrant up` (with provision or at the first time) does `docker-composer up -d`
* If I shutdown the machine (`vagrant halt`) and start it again (`vagrant up`) then `docker-composer start` is used, because the container already exists

Is this possible? I think this is a normal behaviour. I need this, because I must finish an application installation and if I restart the machine, I have to do this again.

**Comment by leighmcculloch** [comment]
@sandrokeil the `-d` option tells docker-compose to run as a daemon, and it won't affect whether the the containers are recreated. Ref: https://docs.docker.com/compose/

If I understand correctly you can do what you want by setting `rebuild: false` in the `vagrant-docker-compose` options in your `Vagrantfile`. If that option is set to true it will delete the container and recreate on `vagrant up`, which isn't what you want. If you're not sure where to put it, share your `Vagrantfile` in here and I'll edit it.

**Comment by sandrokeil** [comment]
@leighmcculloch Thank you for your support. This is the [demo project](https://github.com/sandrokeil/Z-Ray-Doctrine2-Demo) with rebuild: false. Here are my commands:

* `vagrant up`
* `vagrant halt`
* `vagrant up`

And the console output fromt the second vagrant up:
```
==> zraydoctrine2demo: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> zraydoctrine2demo: flag to force provisioning. Provisioners marked to run always will still run.
==> zraydoctrine2demo: Running provisioner: docker_compose...
    zraydoctrine2demo: Checking for Docker Compose installation...
    zraydoctrine2demo: Running docker-compose up...
==> zraydoctrine2demo: stdin: is not a tty
==> zraydoctrine2demo: Recreating vagrant_mariadb_1...
==> zraydoctrine2demo: Recreating vagrant_zendservershopware_1...
```

Are you sure that the rebuild option works?

**Comment by leighmcculloch** [comment]
@sandrokeil Gotcha, I misunderstood. `rebuild: false` will stop the images from being rebuilt from their `Dockerfile`s, but docker-compose is still recreating the containers on `vagrant up` and I can see the same thing happening in the example project.

To fix this, removing `-d` won't be what we need. By default the version installed is `1.3.1` (it's the latest release) and it _always_ recreates containers. Version `1.4.0` will add the feature to not recreate, but warning it's not officially released yet and is still in the release candidate stage.

You can use the release-candidate of `1.4.0` though. Specify an extra option to this plugin: `compose_version: "1.4.0rc3"` and it will use that version instead. You'll need to run `vagrant destroy` then `vagrant up` to start fresh with the new version.

Once `1.4.0` is released I'll make it the default version installed.

Please close this issue if this gets you going.

Ref: https://github.com/docker/compose/releases/tag/1.4.0rc3

**Comment by sandrokeil** [comment]
Thank you very much. This does the job. Can't wait for the new release of docker-compose.

**Comment by hc2p** [comment]
@leighmcculloch just as a heads up, docker-compose 1.4.0 is released now

**Comment by leighmcculloch** [comment]
@hc2p I've just pushed v0.0.5 which defaults to docker-compose 1.4.0. Thanks for pinging me when it was released!

**Comment by hc2p** [comment]
thanks for the immediate update and an awesome plugin!

Am Donnerstag, 27. August 2015 schrieb Leigh McCulloch :
